<?php

namespace App\Repositories;

use App\Criteria\UserCriteria;
use App\Criteria\UserPositionCriteria;
use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use App\Repositories\UserPositionRepository;
use App\Entities\UserPosition;
use App\Validators\UserPositionValidator;

/**
 * Class UserPositionRepositoryEloquent.
 *
 * @package namespace App\Repositories;
 */
class UserPositionRepositoryEloquent extends BaseRepository implements UserPositionRepository
{
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return UserPosition::class;
    }

    

    /**
     * Boot up the repository, pushing criteria
     * @throws
     */
    public function boot()
    {
        $this->pushCriteria(app(UserPositionCriteria::class));
    }

    public function validator()
    {
        return UserPositionValidator::class; // TODO: Change the autogenerated stub
    }

}
